import { configureStore } from "@reduxjs/toolkit";
import { cryptoApi } from "./services/cryptoApi";
import authReducer from "./slices/authSlice";

export default configureStore({
  reducer: {
    auth: authReducer,
    // autogenerated slice reducer by the api
    [cryptoApi.reducerPath]: cryptoApi.reducer,
  },
  // concat the autogenerated middleware
  // middleware: (getDefaultMiddleware) =>
  //   getDefaultMiddleware().concat(cryptoApi.middleware),
});
